apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  init.sql: |
    {{- .Values.config.initSql | nindent 4 }}
