apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: mysql
